### ISSUE TITLE
Exception when deleting a folder that is being watched by SCSS Lint

### ISSUE THREAD

**Issue by keichinger** [Becklyn/becklyn-gulp#1]
An exception is being thrown by SCSS Lint - which also takes down gulp entirely - when you run `gulp dev` while trying to delete a folder that is being watched.

The exception that is thrown is:

``` bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error code 81
Error: Command failed: /bin/sh -c scss-lint /path/to/a/scss/file/that/has/been/removed.scss --config=/project/path/node_modules/becklyn-gulp/tasks/../config/scss-lint.yml --format=XML
```

Not particularly bad as you can simply re-run `gulp dev` but still, we might want to have a look into it and fix it. Apparently this also happens when you move a file into a different folder.

**Comment by apfelbox** [comment]
We don't use SCSS Lint in [kaba](https://github.com/Becklyn/kaba) anymore.
